name:                OrionsOutlaws
version:             0.1.0.0
github:              "PlanetTeamSpeakk/OrionsOutlaws"
license:             BSD-3-Clause
author:              "PlanetTeamSpeak"
maintainer:          "PlanetTeamSpeakk@users.noreply.github.com"
copyright:           "2023 PlanetTeamSpeak"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PlanetTeamSpeakk/OrionsOutlaws#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- hslogger
- GLUT
- bytestring
- file-embed
- random
- time
- JuicyPixels
- gloss-juicy
- vector
- proteaaudio
- aeson
- aeson-pretty
- containers
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  OrionsOutlaws-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - OrionsOutlaws

tests:
  OrionsOutlaws-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - OrionsOutlaws
